### ISSUE TITLE
getRowClassName not changing the table rows background color 

### ISSUE THREAD

**Issue by frankopapic** [croz-ltd/tiller#130]
## Basic information

* Tiller version:
  1.6.1
* Module:
  data-display

## Bug description

The getRowClassName prop in DataTables is not functioning as expected. While the custom background className gets added to the table row element, it is overridden by the default class "bg-slate-50."
### Expected behavior

When a certain condition is met, the table row should change its background color to "bg-red-200."

### Actual behavior

The table row remains with the default background colors "bg-slate-50" or "bg-white," causing the "bg-red-200" class to be overridden.

**Comment by jtomic-croz** [comment]
This happens because of the default theme and default color CSS from tailwind. Some colors are simply "stronger" than others as they come later in the CSS file.

You can try and use important versions of the background at the moment, so instead `bg-red-200` use `!bg-red-200`.

Also. you can try and override tokens for this component and set 
```ts
tableRow: {
    odd: "bg-slate-50",
    even: "bg-white",
},
```
to empty strings, while providing the background logic via `getRowClassName` prop:

```tsx
<DataTable data={[{ id: 1, name: "Test Name", surname: "Test Surname"}, { id: 2, name: "Test Name", surname: "Test Surname"}]}
           tokens={{
               tableRow: {
                   odd: "",
                   even: "",
               }
           }}
    getRowClassName={(values, index) => index % 2 === 0 ? "bg-blue-200" : "bg-red-200"}
>
    <DataTable.Column accessor="id" header="ID"/>
    <DataTable.Column accessor="name" header="Name"/>
    <DataTable.Column accessor="surname" header="Surname"/>
</DataTable>
```

In future, this collision will be fixed with #122
